networks = {"Pyr-PV": dict(N=1000,
                           pyr_ratio=0.8,
                           pv_ratio=0.2,
                            network_type="pyr_pv",
                             pee=0.06,
                             pei=0.42,
                             pie=0.35,
                             pii=0.4,
                             jee=2.5,
                             jie=6.0,
                             jei=5.5,
                             jii=5.0,
                             je0=1.1,
                             ji0=0.6),
            "SOM->Pyr-PV": dict(),
            "SOM<->Pyr-PV": dict(),
            "SOM<->Pyr-PV<-SOM": dict(N=1000,
                           pyr_ratio=0.8,
                           pv_ratio=0.2,
                            som_ratio=0.1,
                            network_type="pyr_pv_som",
                             p_e_e=0.06,
                             p_e_pv=0.42,
                             p_pv_e=0.35,
                             p_pv_pv=0.4,
                             p_som_e=0.35,
                             p_som_pv=0.4,
                             j_e_e=2.5,
                             j_pv_e=6.0,
                             j_som_e=5.5,
                             j_som_pv=5.0,
                             j_e_pv=5.5,
                             j_pv_pv=5.0,
                             j_e_0=1.1,
                             j_som_0=10,
                             j_pv_0=0.6)}
